=== dineshkummarc/ilpalenay/[revisar]/pa_ana/preguntas/openQuestionary.dtd
<!ELEMENT questionaries (questionary*)>
<!ELEMENT questionary (subject+)>
<!ATTLIST questionary
	id ID #REQUIRED
	name CDATA #REQUIRED>
<!ELEMENT subject (question*)>
<!ATTLIST subject
	id ID #REQUIRED
	name CDATA #REQUIRED>
<!ELEMENT question (option+)>
<!ATTLIST question
	text CDATA #REQUIRED>
<!ELEMENT option (#PCDATA)>
<!ATTLIST option
	answer (yes|no) "no">

=== dineshkummarc/ilpalenay/datasource/openqst/matematicabasica.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE subject SYSTEM "openQuestionary.dtd">
<subject id="matematicabasica" name="matematicabasica">
	<question text="cuanto es dos m&#xE1;s dos?">
		<option answer="yes">4</option>
		<option>0</option>
		<option>5</option>
	</question>
	<question text="cuanto es tres elevado a la cuatro?">
		<option answer="yes">81</option>
		<option>27</option>
		<option>57</option>
	</question>
	<question text="cuanto es dos por dos?">
		<option answer="yes">4</option>
		<option>1</option>
		<option>2</option>
	</question>
	<question text="cuanto es dos m&#xE1;s dos?">
		<option answer="yes">4</option>
		<option>0</option>
		<option>5</option>
	</question>
</subject>

=== dineshkummarc/ilpalenay/datasource/openqst/culturageneral.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE subject SYSTEM "openQuestionary.dtd">
<subject id="culturageneral" name="culturageneral">
	<question text="quien la tiene m&#xE1;s grande?">
		<option answer="yes">el dibu</option>
		<option>el vocal</option>
		<option>el guitar</option>
	</question>
	<question text="cuantas vidas tiene un gato?">
		<option answer="yes">una</option>
		<option>siete</option>
		<option>aun es un misterio</option>
	</question>
	<question text="de que pa&#xED;s es aladino?">
		<option answer="yes">de china</option>
		<option>de arabia</option>
		<option>de agrabad</option>
	</question>
	<question text="que oficio ten&#xED;a el papa de pinocho?">
		<option answer="yes">carpintero</option>
		<option>amo de casa</option>
		<option>constructor de marionetas</option>
	</question>
	<question text="cual es el planeta que m&#xE1;s se parece a la tierra?">
		<option answer="yes">venus</option>
		<option>europa</option>
		<option>marte</option>
	</question>
</subject>
